apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockersampleconfigdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DockerExample
  template:
    metadata:
      labels:
        app: DockerExample
    spec:
      containers:
      - name: dockersamplerepos
        image: 856686dockersample.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: DockerExample
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: DockerExample